---
# tasks file for ansible-etc-hosts
- name: pre-reqs (RedHat)
  package:
    name: ["libselinux-python"]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    ansible_os_family == "RedHat" and
    ansible_python_version <= "2"

- name: pre-reqs (RedHat)
  package:
    name: ["python3-libselinux"]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    ansible_os_family == "RedHat" and
    ansible_distribution >= "3"

- name: main | updating /etc/hosts (localhost)
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: true
